### PR TITLE
fix std::chrono not found at compilation time

### PR DESCRIPTION
**Pull request by dave2309**
ref #40

### CODE REVIEW

**Comment by dave2309** [comment]
clang 18
debian sid

**Comment by jcelerier** [comment]
ah, I thought I had this already pushed, let me check as I know for sure it's fixed somewhere

**Comment by dave2309** [comment]
I first compile the project yesterday, very fresh, never did before. I needed that little "fix" to go ahead... :)

**Comment by jcelerier** [comment]
wop, this has long been fixed sorry

**Pull request closed without merging**
